require 'ostruct'
require 'em-ftpd'
require 'fileutils'
require 's3ftp'
require 'sendgrid_webapi'
require 'yaml'
require 'fileutils'

require 'has_s3ftp/server'
require 'has_s3ftp/command'
require 'has_s3ftp/version'